project:
  type: website
  output-dir: docs
website:
  favicon: images/favicon.ico
  navbar:
    search: true
    tools:
      - icon: github
        menu:
          - text: "Source Code"
            href: "https://github.com/OSGeo/grass-tutorials"
          - text: "Report an Issue"
            href: "https://github.com/OSGeo/grass-tutorials/issues"
  page-footer:
    left: |
      Partially supported by US NSF
      [![](/images/logos/NSF_Official_logo_100x100.png){fig-alt="NSF" width=45px}](https://www.nsf.gov/awardsearch/showAward?AWD_ID=2303651)
    center: Content is dual-licensed under [GFDL-1.2-or-later](https://www.gnu.org/licenses/fdl-1.2.html) and [CC-BY-SA-4.0](https://creativecommons.org/licenses/by-sa/4.0/)
    right:
      - icon: github
        href: https://github.com/OSGeo/grass
        aria-label: GRASS on GitHub
      - icon: chat-fill
        href: https://discourse.osgeo.org/c/grass/62
        aria-label: GRASS on Discourse
      - icon: mastodon
        href: https://fosstodon.org/@grassgis
        aria-label: GRASS on Mastodon
      - icon: twitter-x
        href: https://x.com/grassgis
        aria-label: GRASS on X
      - icon: facebook
        href: https://www.facebook.com/groups/GRASS
        aria-label: GRASS on Facebook
      - icon: youtube
        href: https://www.youtube.com/@grass-gis
        aria-label: GRASS on YouTube
execute:
  freeze: auto
format:
  html:
    theme: [brand, pandoc, theme.scss]
    toc: true
    toc-title: Table of Contents
    link-external-newwindow: true
